---
title: "R Notebook"
output: html_notebook
---


```{r}
library(mclust)
source("prediction_ensemble_model.R")
source("ensemble_model.R")
source("select_observation.R")
source("score.R")
source("model_comparison.R")
source("weights_generation.R")
source("simulation.R")
source("visualizationResult.R")

library(caret)
library(rsample)
library(mvtnorm)
library(LaplacesDemon)

library(gtools)
library(DirichletReg)

library(grid)
library(gridExtra)

library(dplyr)

library(ggplot2)
library(GGally)
library(reshape2)  
```



```{r}
data <- read.csv("data.txt")

library(readxl)
ground_truth <- as.data.frame(read_excel("ground_truth.xlsx"))
colnames(ground_truth) <- ground_truth[2,]
ground_truth <- ground_truth[3:78,1:9]
ground_truth <- ground_truth[order(ground_truth$LESION),]

set <- c(114, 174, 476, 490, 604)
df <- t(data[set,seq(1,152,2)])

df <- df[order(rownames(df)),]

Y <- data.frame("Expert1" = ground_truth$`EXPERT 1`,
                "Expert2" = ground_truth$`EXPERT 2`,
                "Expert3" = ground_truth$`EXPERT 3`,
                "Expert4" = ground_truth$`EXPERT 4`,
                "Beginner1" = ground_truth$`BEGINNER 1`,
                "Beginner2" = ground_truth$`BEGINNER 2`,
                "Beginner3" = ground_truth$`BEGINNER 3`)

df_label <- data.frame(df,
                       "truth" = ground_truth$`GROUND TRUTH`,
                       Y)

N= 50

#seeds <- sample(1:1000, 10)
seeds <- 901
```

```{r}
library(gridExtra)

path <- getwd()
pair_data <- df_label[,1:6]
colnames(pair_data) <- c("V113", "V173", "V475", "V489","V603")
pair_plot <- ggpairs(pair_data[,1:5], aes(color = truth, alpha = 0.5), 
        upper = list(continuous = wrap('cor', size = 2)))+
  scale_fill_manual(values=c('red','green','blue')) +
  scale_colour_manual(values=c('red','green','blue'))
ggsave("pairplot.png", pair_plot, dpi = 800)

noisy_label <- df_label[, 6:13]
colnames(noisy_label) <- c("truth", "E1","E2","E3","E4","N1","N2","N3")

misclassification <- noisy_label %>%
  group_by(truth) %>%
  summarize(across(starts_with("E") | starts_with("N"), ~ mean(. != truth) * 100))

misclassification_total <- noisy_label %>%
  summarize(across(starts_with("E") | starts_with("N"), ~ mean(. != truth) * 100))%>%
  mutate(truth = "total", .before = 1)

# Calculate agreement percentages
agreement_counts <- misclassification %>%
  mutate(across(starts_with("E") | starts_with("N"), ~ 100 - .))

# Add a "Total" row
total_agreement <- misclassification_total %>%
  mutate(across(starts_with("E") | starts_with("N"), ~ 100 - .))


# Combine the "Total" row with the agreement_counts data
agreement_counts_with_total <- bind_rows(agreement_counts, total_agreement)

# Melt the data for plotting
melted_agreement <- melt(agreement_counts_with_total, id.vars = "truth", variable.name = "Annotator")
melted_agreement_single <- melt(agreement_counts, id.vars= "truth", variable.name = "Annotator")
melted_agreement_total <- melt(total_agreement, id.vars = "truth", variable.name = "Annotator")
# Create the heatmap
#png(file = paste0(path,"/NoisyLabel.png"))

custom_blue_palette <- c("#EFF3FF", "#BDD7E7", "#6BAED6", "#3182BD", "#08519C")
custom_yellow_blue_palette <- c("#FFFFD9", "#EDF8B1", "#C7E9B4", "#7FCDBB", "#41B6C4", "#1D91C0", "#225EA8", "#253494", "#081D58")
custom_pubu_palette <- c("#F1EEF6", "#D0D1E6", "#A6BDDB", "#74A9CF", "#3690C0", "#0570B0", "#045A8D", "#023858")

selected_palette <- custom_pubu_palette
plot_single <- ggplot(data = melted_agreement_single, aes(x = Annotator, y = truth)) +
  geom_tile(aes(fill = value, height = 1,width = 1), color = "white") +
  scale_fill_gradient(low = selected_palette[1], high =selected_palette[length(selected_palette)-1], limits = c(20, 100))+
  labs(x = "", y = "", title = "Annotators Agreement with Truth Labels") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  #theme(axis.text.x = element_blank()) +  
  scale_y_discrete(position = "left")

plot_total <- ggplot(data = melted_agreement_total, aes(x = Annotator, y = truth)) +
  geom_tile(aes(fill = value, height = 1,width = 1), color = "white") +
  geom_text(aes(label = round(value, 1)), vjust = 1) +
  scale_fill_gradient(low = selected_palette[1], high = selected_palette[length(selected_palette)-1], limits = c(45, 70)) +
  labs(x = "Annotator", y = "", title = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_discrete(position = "left") +
  guides(fill = FALSE)


ggsave("plot_single.png", plot_single, dpi = 300)

# Save the plot_total with high quality
ggsave("plot_total.png", plot_total, dpi = 300)

# Combine the two plots using grid.arrange
png(file = paste0(path,"/GridAgreement.png"), width = 10, height = 8, units = "in", res = 300)
grid_plot <- grid.arrange(
  plot_single, plot_total,
  ncol = 1, nrow = 2,
  heights = c(2, 1)#, widths = c(1, 0.8)
)
grid.draw(grid_plot)
dev.off()
#dev.off()
```


```{r}
for(s in seeds){
  set.seed(s)
  output <- data.frame(row.names = 1:N)
  acc_LDA <- NULL
  acc_QDA <- NULL
  acc_EDDA <- NULL
  
  meanEr_LDA <- NULL
  meanEr_QDA <- NULL
  meanEr_EDDA <- NULL
  
  sigmaEr_LDA <- NULL
  sigmaEr_QDA <- NULL
  sigmaEr_EDDA <- NULL
  
  acc_single <- NULL
  
  start <- Sys.time()
  for (k in 1:N){
    
    df_split <- initial_split(df_label, prop = 2/3,strata = truth)
    train_data <- training(df_split)
    test_data <- testing(df_split)
    
    
    X.train <- train_data[,c(1,2,3,4,5)]
    X.test <- test_data[,c(1,2,3,4,5)]
    Y.test <- test_data$truth
    Y.train <- train_data[,c(7,8,9,10,11,12,13)]
    truth.train <- train_data$truth
    
    # weights generation
    weights <- weights_generation(modelName = c("ExpertBeginner2"),
                                  xtrain = X.train, ytrain_noise = Y.train, 
                                  ytrain = truth.train,ytest = Y.test, Nannotators = 7, N_exp = 4, 
                                  N_beg = 3, positionExpert = c(1,1,1,1,0,1,0),
                                  positionBeginner = c(0,0,0,0,1,0,1))
    
    out <- model_comparison(X.train,X.test,Y.train,truth.train,Y.test,model_weights = weights)
    
    if(k==1){
      acc_LDA <- matrix(NA,N,length(out$ModelNames))
      acc_QDA <- matrix(NA,N,length(out$ModelNames))
      acc_EDDA <- matrix(NA,N,length(out$ModelNames))

      meanEr_LDA <- matrix(NA,N,length(out$ModelNames))
      meanEr_QDA <- matrix(NA,N,length(out$ModelNames))
      meanEr_EDDA <- matrix(NA,N,length(out$ModelNames))

      sigmaEr_LDA <- matrix(NA,N,length(out$ModelNames))
      sigmaEr_QDA <- matrix(NA,N,length(out$ModelNames))
      sigmaEr_EDDA <- matrix(NA,N,length(out$ModelNames))
      
      acc_single <- matrix(NA,N,7)
      
      colnames(acc_LDA) <- out$ModelNames
      colnames(acc_QDA ) <- out$ModelNames
      colnames(acc_EDDA ) <- out$ModelNames

      colnames(meanEr_LDA) <- out$ModelNames
      colnames(meanEr_QDA ) <- out$ModelNames
      colnames(meanEr_EDDA ) <- out$ModelNames

      colnames(sigmaEr_LDA) <- out$ModelNames
      colnames(sigmaEr_QDA ) <- out$ModelNames
      colnames(sigmaEr_EDDA ) <- out$ModelNames
      
      w <- setNames(lapply(replicate(length(out$ModelNames), matrix(NaN, nrow = 50, ncol = 7), simplify = FALSE), as.data.frame), out$ModelNames)
    }
    
    for(name in out$ModelNames){
      acc_LDA[k,name] <- out[[name]]$LDA$accuracy
      acc_QDA[k,name] <- out[[name]]$QDA$accuracy
      acc_EDDA[k,name] <- out[[name]]$LDA$accuracy

      meanEr_LDA[k,name] <- out[[name]]$LDA$meanError
      meanEr_QDA[k,name] <- out[[name]]$QDA$meanError
      meanEr_EDDA[k,name] <- out[[name]]$EDDA$meanError

      sigmaEr_LDA[k,name] <- out[[name]]$LDA$sigmaError
      sigmaEr_QDA[k,name] <- out[[name]]$QDA$sigmaError
      sigmaEr_EDDA[k,name] <- out[[name]]$EDDA$sigmaError
      
      w[[name]][k,] <- weights[[name]]
      
      acc_single[k,] <- out$Acc_single
    }
    
  }
  
  output <- list(Accuracy = list(AccuracyLDA = acc_LDA,
                                 AccuracyQDA = acc_QDA,
                                 AccuracyEDDA = acc_EDDA),
                 MeanError = list(MeanErrorLDA = meanEr_LDA,
                                  MeanErrorQDA = meanEr_QDA,
                                  MeanErrorEDDA = meanEr_EDDA),
                 SigmaError = list(SigmaErrorLDA = sigmaEr_LDA,
                                   SigmaErrorQDA = sigmaEr_QDA,
                                   SigmaErrorEDDA = sigmaEr_EDDA),
                 weights = w,
                 NumberAnnotators = 7,
                 ModelName = out$ModelNames)
  
  print(Sys.time()-start)
  simulationType <- paste(s,"RealDataEN")
  nameFolder <- paste0(simulationType,format(Sys.time(), "%d-%b%Hh%Mm"))
  visualizationResult(output, name = nameFolder)
}

```

```{r}
models_name <- c("GT","E2","N3","PGT","EN","E","MV","ItAlg1","ItAlg2")
indexLDA <- c(1,3,8,16,11,9,13,17,18)
indexQDA <- c(1,3,8,16,11,9,13,19,19)
indexEDDA <- c(1,3,7,16,11,9,13,20,21)
```

```{r}
acc_LDA <- output$Accuracy$AccuracyLDA[,indexLDA]
acc_QDA <- output$Accuracy$AccuracyQDA[,indexQDA]
acc_EDDA <- output$Accuracy$AccuracyEDDA[,indexEDDA]

MSE <- output$MeanError$MeanErrorLDA
MSE <- MSE[,indexLDA]
colnames(MSE) <- models_name

CSE_LDA <- output$SigmaError$SigmaErrorLDA
CSE_LDA <- CSE_LDA[,indexLDA]
colnames(CSE_LDA) <- models_name

CSE_QDA <- output$SigmaError$SigmaErrorQDA
CSE_QDA <- CSE_QDA[,indexQDA]
colnames(CSE_QDA) <- models_name

CSE_EDDA <- output$SigmaError$SigmaErrorEDDA
CSE_EDDA <- CSE_EDDA[,indexEDDA]
colnames(CSE_EDDA) <- models_name

weightsPGT1 <- w$someGT

weightsMV1 <- w$MV1

weightsMV2 <- w$MV2

weightsItAlg1LDA1 <- w$IterAlg1LDA

weightsItAlg2LDA1 <- w$IterAlg2LDA

weightsItAlg1QDA1 <- w$IterAlg1QDA

weightsItAlg2QDA1 <- w$IterAlg2QDA

weightsItAlg1EDDA1 <- w$IterAlg1EDDA

weightsItAlg2EDDA1 <- w$IterAlg2EDDA
```



```{r}
library("ggplot2")
library("patchwork")
library("gridExtra")
annotator_name <- c("E1","E2","E3","E4","N1","N2","N3")
annotator_class <- c("E","E","E","E","N","N","N")

weights_data_PGT <- data.frame(
  weights = c(as.matrix(weightsPGT1)/rowSums(as.matrix(weightsPGT1))),
  annotator = rep(annotator_name, each = nrow(weightsPGT1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsPGT1))
)

weights_data_MV2 <- data.frame(
  weights = c(as.matrix(weightsMV2)/rowSums(as.matrix(weightsMV2))),
  annotator = rep(annotator_name, each = nrow(weightsMV2)),
  annotatorClass = rep(annotator_class, each = nrow(weightsMV2))
)

weights_data_italg1LDA <- data.frame(
  weights = c(as.matrix(weightsItAlg1LDA1)/rowSums(as.matrix(weightsItAlg1LDA1))),
  annotator = rep(annotator_name, each = nrow(weightsItAlg1LDA1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsItAlg1LDA1))
)

weights_data_italg2LDA <- data.frame(
  weights = c(as.matrix(weightsItAlg2LDA1)/rowSums(as.matrix(weightsItAlg2LDA1))),
  annotator = rep(annotator_name, each = nrow(weightsItAlg2LDA1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsItAlg2LDA1))
)

path <- getwd()


boxPGT <- ggplot(weights_data_PGT, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "PGT") 


boxMV <- ggplot(weights_data_MV2, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2) +
  labs(x = "Annotator", y = "Weights", title = "MV") 



boxItAlg1 <- ggplot(weights_data_italg1LDA, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "ItAlg1") 



boxItAlg2 <- ggplot(weights_data_italg2LDA, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "ItAlg2") 

png(file = paste0(path,"/BoxSim.png"), width = 10, height = 8, units = "in", res = 300)
grid_plot <- grid.arrange(
  boxPGT, boxMV, boxItAlg1, boxItAlg2,
  ncol = 2, nrow = 2
  #heights = c(2, 1)#, widths = c(1, 0.8)
)
grid.draw(grid_plot)
dev.off()
```

```{r}
df_split <- initial_split(df_label, prop = 2/3,strata = truth)
train_data <- training(df_split)
test_data <- testing(df_split)


X.train <- train_data[,c(1,2,3,4,5)]
X.test <- test_data[,c(1,2,3,4,5)]
Y.test <- test_data$truth
Y.train <- train_data[,c(7,8,9,10,11,12,13)]
truth.train <- train_data$truth

positionExpert = c(1,1,1,1,0,1,0)
positionNovice = c(0,0,0,0,1,0,1)
w_exp <- rep(0.8/5,7)*positionExpert
w_beg <- rep(0.2/2,7)*positionNovice
weights <-  (w_exp+w_beg)

ensemble_model_LDA <- ensemble_model(X.train,Y.train, modelName = "LDA", w = weights)
prediction_ensemble_model_LDA <- prediction_ensemble_model(X.test, ensemble_model_LDA, Ytest = Y.test)

#png(file = paste0(path,"/ConfusionMatrix.png"))
cm <- confusionMatrix(data = as.factor(prediction_ensemble_model_LDA$classification), reference = as.factor(Y.test))
plt <- as.data.frame(cm$table)
plt$Prediction <- factor(plt$Prediction, levels=levels(plt$Prediction))
ggplot(plt, aes(Prediction,Reference, fill = Freq)) + geom_tile() + geom_text(aes(label=Freq)) + scale_fill_gradient(low="cadetblue1",high="cornflowerblue")+ labs(x="True label",y="Predicted label")+
  coord_fixed(ratio = 1)
#dev.off()

```

```{r}
boxplot(acc_single)
  
```




