---
title: "Simulation"
output: html_document
date: "2023-03-30"
---
# **Simulation study**

```{r}
library(mclust)
source("model/prediction_ensemble_model.R")
source("model/ensemble_model.R")
source("model/select_observation.R")
source("model/score.R")
source("model/model_comparison.R")
source("model/weights_generation.R")
source("model/simulation.R")
source("model/visualizationResult.R")

library(caret)
library(rsample)
library(mvtnorm)
library(LaplacesDemon)

library(gtools)
library(DirichletReg)

library(grid)
library(gridExtra)

library(ggplot2)
library(reshape2)

library(MASS)
library(clusterGeneration)
```

# **Simulation for Scenario 1**

Input data

```{r}
x1 <- rmvnorm(n=500, mean=c(2,2))
x2 <- rmvnorm(n=500, mean=c(-2,-2))
x3 <- rmvnorm(n=500, mean=c(0,0))

X <- rbind(x1,x2,x3)
colors <- c(rep('green', 500), rep('red', 500), rep('blue', 500))
shapes <- c(rep(16, 500), rep(16, 500), rep(16, 500))

plot(X, pch = shapes,col = colors, xlab = "Feature 1", ylab = "Feature 2", main = "Scenario 1")
legend("topright", legend = c("Group 1", "Group 2", "Group 3"), fill = c("green", "red", "blue"))


```

Script to run the simulation on all the models, results are saved in Folder "1Simulation%d-%b%Hh%Mm"

```{r}
p = 2
mu <- rbind(rep(2,p),rep(-2,p),rep(0,p))
Nobs = c(50)

count <- 1

#seeds <- c(798,386)#sample(1:1000, 100)
# seeds <- 43
set.seed(43)

result <- simulation(S = 50, mu = mu, N= Nobs)
    
# Set the name of the folder for the result
simulationType <- 1
nameFolder <- paste0(simulationType,"Simulation",format(Sys.time(), "%d-%b%Hh%Mm"))
visualizationResult(result, name = nameFolder)

```

# **Simulation for Scenario 2**

```{r}
colors <- c(rep('green', 500), rep('red', 500), rep('blue', 500))
shapes <- c(rep(16, 500), rep(16, 500), rep(16, 500))


set.seed(11)
Sigma1 <- genPositiveDefMat(2)
Sigma2 <- genPositiveDefMat(2)
Sigma3 <- genPositiveDefMat(2) #798 386
x1 <- rmvnorm(n=500, mean=c(2,2),sigma=Sigma1$Sigma/4)
x2 <- rmvnorm(n=500, mean=c(-2,-2),sigma=Sigma2$Sigma/4)
x3 <- rmvnorm(n=500, mean=c(0,0),sigma=Sigma3$Sigma/4)
X <- rbind(x1,x2,x3)
plot(X, col = colors, pch = shapes,xlab = "Feature 1", ylab = "Feature 2", main = "Scenario 2")
legend("topright", legend = c("Group 1", "Group 2", "Group 3"), fill = c("green", "red", "blue"))

```

Script to run the simulation on all the models, results are saved in Folder "2Simulation%d-%b%Hh%Mm"

```{r}
p = 2
mu <- rbind(rep(2,p),rep(-2,p),rep(0,p))
Nobs = c(50)

count <- 1

set.seed(43)

result <- simulation(S = 50, mu = mu, sigma = rbind(Sigma1$Sigma/4,Sigma2$Sigma/4,Sigma3$Sigma/4), N= Nobs)
    
# Set the name of the folder for the result
simulationType <- 2
nameFolder <- paste0(simulationType,"Simulation",format(Sys.time(), "%d-%b%Hh%Mm"))
visualizationResult(result, name = nameFolder)

```

Generate boxplot reported in the paper

```{r}
models_name <- c("GT","E2","N3","PGT","EN","E","MV","ItAlg1","ItAlg2")
indexLDA <- c(1,3,8,15,11,9,13,16,17)
indexQDA <- c(1,3,8,15,11,9,13,18,18)
indexEDDA <- c(1,3,7,15,11,9,13,19,20)
```


```{r}
MSE <- result$MeanError$MeanErrorLDA
MSE <- MSE[,indexLDA]
colnames(MSE) <- models_name

CSE_LDA <- result$SigmaError$SigmaErrorLDA
CSE_LDA <- CSE_LDA[,indexLDA]
colnames(CSE_LDA) <- models_name

CSE_QDA <- result$SigmaError$SigmaErrorQDA
CSE_QDA <- CSE_QDA[,indexQDA]
colnames(CSE_QDA) <- models_name

CSE_EDDA <- result$SigmaError$SigmaErrorEDDA
CSE_EDDA <- CSE_EDDA[,indexEDDA]
colnames(CSE_EDDA) <- models_name

weightsPGT1 <- result$weights$someGT

weightsMV1 <- result$weights$MV1

weightsMV2 <- result$weights$MV2

weightsItAlg1LDA1 <- result$weights$IterAlg1LDA

weightsItAlg2LDA1 <- result$weights$IterAlg2LDA

weightsItAlg1QDA1 <- result$weights$IterAlg1QDA

weightsItAlg2QDA1 <- result$weights$IterAlg2QDA

weightsItAlg1EDDA1 <- result$weights$IterAlg1EDDA

weightsItAlg2EDDA1 <- result$weights$IterAlg2EDDA
```

```{r}
library("ggplot2")
library("patchwork")

# Create the mse_data data frame
mse_data <- data.frame(
  MSE = c(MSE),
  Model = rep(models_name, each = nrow(MSE))
)

ggplot(mse_data, aes(x = Model, y = MSE, fill = Model)) +
  geom_boxplot(fill=c("lightgray","lightgray","lightgray"  ,"#999999","#999999" ,"#999999" ,"#999999","#999999" ,"#999999"  ), color="black") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(MSE[,1]), color = "red")+
  geom_hline(yintercept=median(MSE[,5]), linetype="dashed", color = "red")

```

```{r}
cse_dataLDA <- data.frame(CSE = c(CSE_LDA), Model = rep(models_name, each = nrow(MSE)))
cse_dataQDA <- data.frame(CSE = c(CSE_QDA), Model = rep(models_name, each = nrow(MSE)))
cse_dataEDDA <- data.frame(CSE = c(CSE_EDDA), Model = rep(models_name, each = nrow(MSE)))

ggplot(cse_dataLDA, aes(x = Model, y = CSE, fill = Model)) +
  geom_boxplot(fill = c("lightblue","lightblue","lightblue","deepskyblue","deepskyblue","deepskyblue","deepskyblue","deepskyblue","deepskyblue"), color = "black") +
  labs(title = "LDA") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(CSE_LDA[,1]), color = "red")+
  geom_hline(yintercept=median(CSE_LDA[,5]), linetype="dashed", color = "red")+
  ylim(0,7)

ggplot(cse_dataQDA, aes(x = Model, y = CSE, fill = Model)) +
  geom_boxplot(fill = c("#CC99FF","#CC99FF","#CC99FF","purple","purple","purple","purple","purple","purple"), color = "black") +
  labs(title = "QDA") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(CSE_QDA[,1]), color = "red")+
  geom_hline(yintercept=median(CSE_QDA[,5]), linetype="dashed", color = "red")+
  ylim(0,7)

ggplot(cse_dataEDDA, aes(x = Model, y = CSE, fill = Model)) +
  geom_boxplot(fill = c("#FFF592","#FFF592","#FFF592","#FFEB3B","#FFEB3B","#FFEB3B","#FFEB3B","#FFEB3B","#FFEB3B"), color = "black") +
  labs(title = "EDDA") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(CSE_EDDA[,1]), color = "red")+
  geom_hline(yintercept=median(CSE_EDDA[,5]), linetype="dashed", color = "red")+
  ylim(0,7)

```

```{r}
annotator_name <- c("E1","E2","E3","E4","N1","N2","N3")
annotator_class <- c("E","E","E","E","N","N","N")

weights_data_PGT <- data.frame(
  weights = c(as.matrix(weightsPGT1)/rowSums(as.matrix(weightsPGT1))),
  annotator = rep(annotator_name, each = nrow(weightsPGT1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsPGT1))
)

weights_data_MV2 <- data.frame(
  weights = c(as.matrix(weightsMV2)/rowSums(as.matrix(weightsMV2))),
  annotator = rep(annotator_name, each = nrow(weightsMV2)),
  annotatorClass = rep(annotator_class, each = nrow(weightsMV2))
)

weights_data_italg1LDA <- data.frame(
  weights = c(as.matrix(weightsItAlg1LDA1)/rowSums(as.matrix(weightsItAlg1LDA1))),
  annotator = rep(annotator_name, each = nrow(weightsItAlg1LDA1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsItAlg1LDA1))
)

weights_data_italg2LDA <- data.frame(
  weights = c(as.matrix(weightsItAlg2LDA1)/rowSums(as.matrix(weightsItAlg2LDA1))),
  annotator = rep(annotator_name, each = nrow(weightsItAlg2LDA1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsItAlg2LDA1))
)

path <- getwd()


boxPGT <- ggplot(weights_data_PGT, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "PGT") +
  theme(axis.text.x = element_text(size = 16),  # Adjust the x-axis label size (change 12 to your desired size)
        axis.text.y = element_text(size = 16),  # Adjust the y-axis label size (change 12 to your desired size)
        axis.title.x = element_text(size = 20), # Adjust the x-axis title size (change 14 to your desired size)
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 22)) 


boxMV <- ggplot(weights_data_MV2, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2) +
  labs(x = "Annotator", y = "Weights", title = "MV") +
  theme(axis.text.x = element_text(size = 16),  # Adjust the x-axis label size (change 12 to your desired size)
        axis.text.y = element_text(size = 16),  # Adjust the y-axis label size (change 12 to your desired size)
        axis.title.x = element_text(size = 20), # Adjust the x-axis title size (change 14 to your desired size)
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 22)) 


boxItAlg1 <- ggplot(weights_data_italg1LDA, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "ItAlg1") +
  theme(axis.text.x = element_text(size = 16),  # Adjust the x-axis label size (change 12 to your desired size)
        axis.text.y = element_text(size = 16),  # Adjust the y-axis label size (change 12 to your desired size)
        axis.title.x = element_text(size = 20), # Adjust the x-axis title size (change 14 to your desired size)
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 22)) 


boxItAlg2 <- ggplot(weights_data_italg2LDA, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "ItAlg2") +
  theme(axis.text.x = element_text(size = 16),  
        axis.text.y = element_text(size = 16),  
        axis.title.x = element_text(size = 20), 
        axis.title.y = element_text(size = 20),
        plot.title = element_text(size = 22)) 


grid_plot <- grid.arrange(
  boxPGT, boxMV, boxItAlg1, boxItAlg2,
  ncol = 2, nrow = 2
)
grid.draw(grid_plot)

```
