---
title: "Simulation"
output: html_document
date: "2023-03-30"
---


```{r}
library(mclust)
source("prediction_ensemble_model.R")
source("ensemble_model.R")
source("select_observation.R")
source("score.R")
source("model_comparison.R")
source("weights_generation.R")
source("simulation.R")
source("visualizationResult.R")

library(caret)
library(rsample)
library(mvtnorm)
library(LaplacesDemon)

library(gtools)
library(DirichletReg)

library(grid)
library(gridExtra)

library(ggplot2)
library(reshape2)

library(MASS)
library(clusterGeneration)# (genPositiveDefMat))
```


```{r}
x1 <- rmvnorm(n=500, mean=c(2,2))
x2 <- rmvnorm(n=500, mean=c(-2,-2))
x3 <- rmvnorm(n=500, mean=c(0,0))

X <- rbind(x1,x2,x3)
colors <- c(rep('green', 500), rep('red', 500), rep('blue', 500))
shapes <- c(rep(16, 500), rep(16, 500), rep(16, 500))
#png(file = "~/GitHub/Thesis/SimulationSettingPlot//I.png")
plot(X, pch = shapes,col = colors, xlab = "Feature 1", ylab = "Feature 2", main = "Scenario 1")
legend("topright", legend = c("Group 1", "Group 2", "Group 3"), fill = c("green", "red", "blue"))
#dev.off()

```

```{r}
seeds <- sample(1:1000, 10)
# Sigma1 <- genPositiveDefMat(2)
# Sigma2 <- genPositiveDefMat(2)
# Sigma3 <- genPositiveDefMat(2)
# 
# 
# x1 <- rmvnorm(n=500, mean=c(2,2),sigma=Sigma1$Sigma/2)
# x2 <- rmvnorm(n=500, mean=c(-2,-2),sigma=Sigma2$Sigma/2)
# x3 <- rmvnorm(n=500, mean=c(0,0),sigma=Sigma3$Sigma/2)
# X <- rbind(x1,x2,x3)
colors <- c(rep('green', 500), rep('red', 500), rep('blue', 500))
shapes <- c(rep(16, 500), rep(16, 500), rep(16, 500))
#png(file = "~/GitHub/Thesis/SimulationSettingPlot/Sigma.png")

for (s in seeds){
  set.seed(11)
  Sigma1 <- genPositiveDefMat(2)
  Sigma2 <- genPositiveDefMat(2)
  Sigma3 <- genPositiveDefMat(2) #798 386
  x1 <- rmvnorm(n=500, mean=c(2,2),sigma=Sigma1$Sigma/5)
  x2 <- rmvnorm(n=500, mean=c(-2,-2),sigma=Sigma2$Sigma/5)
  x3 <- rmvnorm(n=500, mean=c(0,0),sigma=Sigma3$Sigma/5)
  X <- rbind(x1,x2,x3)
  plot(X, col = colors, pch = shapes,xlab = "Feature 1", ylab = "Feature 2", main = "Scenario 2")
  legend("topright", legend = c("Group 1", "Group 2", "Group 3"), fill = c("green", "red", "blue"))
  
  #dev.off() 
}
png(file = "Scenario_2.png")
plot(X, col = colors, pch = shapes,xlab = "Feature 1", ylab = "Feature 2", main = "Scenario 2")
  legend("topright", legend = c("Group 1", "Group 2", "Group 3"), fill = c("green", "red", "blue"))
#161
dev.off()
scenario2_plot
```


```{r}
# set.seed(669)
# Sigma1 <- genPositiveDefMat(2)
# Sigma2 <- genPositiveDefMat(2)
# Sigma3 <- genPositiveDefMat(2) #798 386
# x1 <- rmvnorm(n=500, mean=c(4,4),sigma=Sigma1$Sigma)
# x2 <- rmvnorm(n=500, mean=c(-4,-4),sigma=Sigma2$Sigma)
# x3 <- rmvnorm(n=500, mean=c(0,0),sigma=Sigma3$Sigma)
# X <- rbind(x1,x2,x3)
# plot(X, col = colors, pch = shapes,xlab = "Feature 1", ylab = "Feature 2", main = paste("Scenario 2"))
# legend("topright", legend = c("Group 1", "Group 2", "Group 3"), fill = c("green", "red", "blue"))
```


```{r}
p = 2
mu <- rbind(rep(2,p),rep(-2,p),rep(0,p))
N = c(50)

count <- 1

#seeds <- c(798,386)#sample(1:1000, 100)
seeds <- 43

for(s in seeds){
  set.seed(s)
  for(nobs in N){
    result <- simulation(S = 50, mu = mu, 
                         sigma = rbind(Sigma1$Sigma/5,Sigma2$Sigma/5,Sigma3$Sigma/5),
                         N= nobs)
    
    # Set the name of the folder for the result
    simulationType <- s
    nameFolder <- paste0(simulationType,"Simulation",format(Sys.time(), "%d-%b%Hh%Mm"))
    visualizationResult(result, name = nameFolder)
  }
}


```

One simulation

```{r}
S = 50
mu = rbind(c(2,2),c(-2,-2),c(0,0))
p=2
#sigma = rbind(diag(2),diag(2),diag(2))
sigma = rbind(Sigma1$Sigma,Sigma2$Sigma,Sigma3$Sigma)
N = 50
Y <- c(rep("G1",N),rep("G2",N),rep("G3",N))
alpha_beg = rbind(c(7,4,4),c(4,7,4),c(4,4,7))
alpha_exp = rbind(c(12,4,4),c(4,12,4),c(4,4,12))
Nannotators = 7
N_exp = 4
N_beg = 3
N_class = 3
weights = NULL

z_beg <- NULL
z_exp <- NULL
for(n in 1:N_class){
  z_beg <- rbind(z_beg, rdirichlet(N,alpha=alpha_beg[n,]))
  z_exp <- rbind(z_exp, rdirichlet(N,alpha=alpha_exp[n,]))
}

# Initialize Accurac, Mean Error and Sigma Error matrix
acc_LDA <- NULL
acc_QDA <- NULL
acc_EDDA <- NULL

meanEr_LDA <- NULL
meanEr_QDA <- NULL
meanEr_EDDA <- NULL

sigmaEr_LDA <- NULL
sigmaEr_QDA <- NULL
sigmaEr_EDDA <- NULL

# Features
X <- NULL
for(n in 1:N_class){
  X <- rbind(X,rmvnorm(n=N ,mean=mu[n,],sigma=sigma[c(1:p) + (n-1)*p,]))
}

# Y noise experts
Y_noise_exp <- matrix(NA,nrow(z_exp),N_exp)
name_exp <- NULL
for(j in 1:nrow(z_exp)){
  mult_jk <- rmultinom(N_exp,1,z_exp[c(j),])
  for (k in 1:N_exp){
    Y_noise_exp[j,k] <- which(mult_jk[,k]==1)
    
    if(j==1){
      name_exp <- cbind(name_exp, paste0("Expert",k)) 
    }
  }
}

# Y noise beginners
Y_noise_beg <- matrix(NA,nrow(z_beg),N_beg)
name_beg <- NULL
for(j in 1:nrow(z_beg)){
  mult_jk <- rmultinom(N_beg,1,z_beg[c(j),])
  for (k in 1:N_beg){
    Y_noise_beg[j,k] <- which(mult_jk[,k]==1)
    
    if(j==1){
      name_beg <- cbind(name_beg, paste0("Beginner",k))
    }
  }
}
Y_noise <- cbind(Y_noise_exp,Y_noise_beg)
colnames(Y_noise) <- cbind(name_exp,name_beg)

for(n in 1:N_class){
  Y_noise[Y_noise==n] <- paste0("G",n)
}

# Train test set
XY <- data.frame(X,
                 Y_noise,
                 label = Y)
df_split <- initial_split(XY, prop = 2/3,strata = label)
train_data <- training(df_split)
test_data <- testing(df_split)
X.train <- train_data[,c(1:p)]
X.test <- test_data[,c(1:p)]
truth.train <- train_data$label
Y.test <- test_data$label
Y.train <- train_data[,c((p+1):(Nannotators+p))]

# Weights generation
if(is.null(weights)){
  weights <- weights_generation(xtrain = X.train, ytrain_noise = Y.train, ytrain = truth.train,ytest = Y.test, 
                                Nannotators = Nannotators, N_exp = N_exp, N_beg = N_beg)  
}

# Model comparison
parameters <- list()
class_name <- unique(truth.train)
num_class <- length(class_name)

for(k in 1:num_class){
  class_k <- class_name[k]
  parameters$mu[[class_k]] <- mu[k,]
  parameters$sigma[[class_k]] <- sigma[((k - 1) * p+1):(k*p),]
}

mods <- model_comparison(X.train,X.test,Y.train,truth.train,Y.test,model_weights = weights,
                         parameters = parameters)

```

Boxplot

```{r}
models_name <- c("GT","E2","N3","PGT","EN","E","MV","ItAlg1","ItAlg2")
indexLDA <- c(1,3,8,16,11,9,13,17,18)
indexQDA <- c(1,3,8,16,11,9,13,19,19)
indexEDDA <- c(1,3,7,16,11,9,13,20,21)
```

```{r}
MSE <- result$MeanError$MeanErrorLDA
MSE <- MSE[,indexLDA]
colnames(MSE) <- models_name

CSE_LDA <- result$SigmaError$SigmaErrorLDA
CSE_LDA <- CSE_LDA[,indexLDA]
colnames(CSE_LDA) <- models_name

CSE_QDA <- result$SigmaError$SigmaErrorQDA
CSE_QDA <- CSE_QDA[,indexQDA]
colnames(CSE_QDA) <- models_name

CSE_EDDA <- result$SigmaError$SigmaErrorEDDA
CSE_EDDA <- CSE_EDDA[,indexEDDA]
colnames(CSE_EDDA) <- models_name

weightsPGT1 <- result$weights$someGT

weightsMV1 <- result$weights$MV1

weightsMV2 <- result$weights$MV2

weightsItAlg1LDA1 <- result$weights$IterAlg1LDA

weightsItAlg2LDA1 <- result$weights$IterAlg2LDA

weightsItAlg1QDA1 <- result$weights$IterAlg1QDA

weightsItAlg2QDA1 <- result$weights$IterAlg2QDA

weightsItAlg1EDDA1 <- result$weights$IterAlg1EDDA

weightsItAlg2EDDA1 <- result$weights$IterAlg2EDDA
```

```{r}
library("ggplot2")
library("patchwork")
# Create the mse_data data frame
mse_data <- data.frame(
  MSE = c(MSE),
  Model = rep(models_name, each = nrow(MSE))
)
png(file = "C:/Users/giuli/Documents/GitHub/Thesis/SimulationResult/43Simulation22-ago23h11m/BoxplotMSE.png")
# Create the ggplot boxplot
ggplot(mse_data, aes(x = Model, y = MSE, fill = Model)) +
  geom_boxplot(fill=c("lightgray","lightgray","lightgray"  ,"#999999","#999999" ,"#999999" ,"#999999","#999999" ,"#999999"  ), color="black") +
  #labs(title = "Mean Squared Error (MSE)") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(MSE[,1]), color = "red")+
  geom_hline(yintercept=median(MSE[,5]), linetype="dashed", color = "red")
dev.off()
```

```{r}
cse_dataLDA <- data.frame(CSE = c(CSE_LDA), Model = rep(models_name, each = nrow(MSE)))
cse_dataQDA <- data.frame(CSE = c(CSE_QDA), Model = rep(models_name, each = nrow(MSE)))
cse_dataEDDA <- data.frame(CSE = c(CSE_EDDA), Model = rep(models_name, each = nrow(MSE)))

png(file = "C:/Users/giuli/Documents/GitHub/Thesis/SimulationResult/43Simulation22-ago23h11m/BoxplotCSELDA2.png")
ggplot(cse_dataLDA, aes(x = Model, y = CSE, fill = Model)) +
  geom_boxplot(fill = c("lightblue","lightblue","lightblue","deepskyblue","deepskyblue","deepskyblue","deepskyblue","deepskyblue","deepskyblue"), color = "black") +
  labs(title = "LDA") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(CSE_LDA[,1]), color = "red")+
  geom_hline(yintercept=median(CSE_LDA[,5]), linetype="dashed", color = "red")+
  ylim(0,7)
dev.off()
png(file = "C:/Users/giuli/Documents/GitHub/Thesis/SimulationResult/43Simulation22-ago23h11m/BoxplotCSEQDA2.png")
ggplot(cse_dataQDA, aes(x = Model, y = CSE, fill = Model)) +
  geom_boxplot(fill = c("#CC99FF","#CC99FF","#CC99FF","purple","purple","purple","purple","purple","purple"), color = "black") +
  labs(title = "QDA") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(CSE_QDA[,1]), color = "red")+
  geom_hline(yintercept=median(CSE_QDA[,5]), linetype="dashed", color = "red")+
  ylim(0,7)
dev.off()
png(file = "C:/Users/giuli/Documents/GitHub/Thesis/SimulationResult/43Simulation22-ago23h11m/BoxplotCSEEDDA2.png")
ggplot(cse_dataEDDA, aes(x = Model, y = CSE, fill = Model)) +
  geom_boxplot(fill = c("#FFF592","#FFF592","#FFF592","#FFEB3B","#FFEB3B","#FFEB3B","#FFEB3B","#FFEB3B","#FFEB3B"), color = "black") +
  labs(title = "EDDA") +
  scale_x_discrete(limits=models_name)+
  geom_hline(yintercept=median(CSE_EDDA[,1]), color = "red")+
  geom_hline(yintercept=median(CSE_EDDA[,5]), linetype="dashed", color = "red")+
  ylim(0,7)
dev.off()
```


```{r}
annotator_name <- c("E1","E2","E3","E4","N1","N2","N3")
annotator_class <- c("E","E","E","E","N","N","N")

weights_data_PGT <- data.frame(
  weights = c(as.matrix(weightsPGT1)/rowSums(as.matrix(weightsPGT1))),
  annotator = rep(annotator_name, each = nrow(weightsPGT1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsPGT1))
)

weights_data_MV2 <- data.frame(
  weights = c(as.matrix(weightsMV2)/rowSums(as.matrix(weightsMV2))),
  annotator = rep(annotator_name, each = nrow(weightsMV2)),
  annotatorClass = rep(annotator_class, each = nrow(weightsMV2))
)

weights_data_italg1LDA <- data.frame(
  weights = c(as.matrix(weightsItAlg1LDA1)/rowSums(as.matrix(weightsItAlg1LDA1))),
  annotator = rep(annotator_name, each = nrow(weightsItAlg1LDA1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsItAlg1LDA1))
)

weights_data_italg2LDA <- data.frame(
  weights = c(as.matrix(weightsItAlg2LDA1)/rowSums(as.matrix(weightsItAlg2LDA1))),
  annotator = rep(annotator_name, each = nrow(weightsItAlg2LDA1)),
  annotatorClass = rep(annotator_class, each = nrow(weightsItAlg2LDA1))
)

path <- getwd()


boxPGT <- ggplot(weights_data_PGT, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "PGT") 


boxMV <- ggplot(weights_data_MV2, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2) +
  labs(x = "Annotator", y = "Weights", title = "MV") 



boxItAlg1 <- ggplot(weights_data_italg1LDA, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "ItAlg1") 



boxItAlg2 <- ggplot(weights_data_italg2LDA, aes(x = annotator, y = weights, fill = annotatorClass)) +
  geom_boxplot(fill = c("#4393C3","#4393C3","#4393C3","#4393C3","#92C5DE","#92C5DE","#92C5DE"), color = "black") +
  ylim(0.08,0.2)+
  labs(x = "Annotator", y = "Weights", title = "ItAlg2") 

png(file = paste0(path,"/Box.png"), width = 10, height = 8, units = "in", res = 300)
grid_plot <- grid.arrange(
  boxPGT, boxMV, boxItAlg1, boxItAlg2,
  ncol = 2, nrow = 2
  #heights = c(2, 1)#, widths = c(1, 0.8)
)
grid.draw(grid_plot)
dev.off()
```

